### ISSUE TITLE
留言

### ISSUE THREAD

**Issue by lupus721** [Cat7373/Blog#6]
哈哈，留言回复竟然这么奇特的一个方式

https://blog.cat73.org/2017/07/16/https/

以前也是这么折腾的，但是免费证书还是有一系列的问题，最后全部交给cloudflare解决的，基本一劳永逸，我觉得也可以试试

**Comment by Cat7373** [comment]
什么问题。。我并没有啥问题呀 0.0

**Comment by lupus721** [comment]
比如说免费的证书3个月还是半年需要更新一次，如果ip地址被ban，换ip还需要重新申请

**Comment by Cat7373** [comment]
换 IP 不需要重新申请，3 个月过期但可以全自动续期

**Comment by lupus721** [comment]
还有点小问题，我有一堆域名。。。申请证书什么的也ok么

**Comment by Cat7373** [comment]
目前`letsencrypt`不支持泛域名证书，而且一张证书最多只能有`100`个域名

不过根据计划明年就支持泛域名了 0.0
